### ISSUE TITLE
downloading failed on kodi 14

### ISSUE THREAD

**Issue by yuvalp777** [XBMCil/service.subtitles.torec#10]
Hello
 I have a new smart box called least b4a build on android 4.4.
 I instaled the last versionof force add-on but when I am trying to download a subtitle it is  dont working and write downloading failed.
Here is the log file
http://pastebin.com/AiiDmWQg

Plz help me

**Comment by slmosl** [comment]
Hey, this issue is a duplicate of #11.
I've created a version that should work this issue out (1.0.5).
Please have a go a it (https://github.com/XBMCil/service.subtitles.torec/archive/v1.0.5.zip)
