### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by Yossiweb** [XBMCil/service.subtitles.torec#12]
Hi there,
first, i want to say that this is n excellent add-on :)

I'm using Kodi 14.0 on windows 7 64bit, when i try to search and download a subtitle in the add-on, the search is perfect, yet, when i try to download the subtitle i get error message "failed to download subtitle".

**Comment by YanivSa** [comment]
+1.
Stopped working (latest Kodi on openelec).

**Comment by myakove** [comment]
Please provide log.

**Comment by YanivSa** [comment]
7:15:46 T:140643418482432   ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/l
bs4/element.py:1413: UserWarning: has_key is deprecated. Use has_attr("value") instead.
                                             key))
7:15:46 T:140643418482432  NOTICE: ### [TorecSubtitlesDownloader] - Found relevant meta
ta
7:15:46 T:140643418482432  NOTICE: ### [__main__] - search took 3.044394
7:15:46 T:140643418482432  NOTICE: ### [__main__] - Found most relevant option to be :
V x264-BATV
7:15:46 T:140643418482432  NOTICE: ### [__main__] - Overall search took 3.057601
7:16:06 T:140643980461824  NOTICE: ES: Client  from 10.0.0.5 timed out
                                                                       1254,42       Bo

**Comment by Yossiweb** [comment]
Hello,
I have no idea where to find the log. Clean you please guide me?

I found the element py file, but didn't know exactly what to do with it...

Thanks again,
yossi

**Comment by slmosl** [comment]
fixed in v1.0.9
