### ISSUE TITLE
torec 1.05 can't see nothing after downloaded

### ISSUE THREAD

**Issue by ghost73** [XBMCil/service.subtitles.torec#15]
hi
i use openelec 6.95 (kodi 16.1)
and also i use torec 1.05,when i download subtitles,its ok,but can't see nothing.
i should disable the subtitles that i already downloaded from sound setting,and apply it again and then it appears
ok.
i cant use kodi more than 16.1,because the skin that i used.
so please help.
thanks

**Comment by slmosl** [comment]
hey @ghost73 , can you provide a relevant log?
