### ISSUE TITLE
The torec site has blocked addon again

### ISSUE THREAD

**Issue by itzikg** [XBMCil/service.subtitles.torec#20]
@slmosl @gklein @sagiben
http://pastebin.com/J8FAAzXX

**Comment by gklein** [comment]
@itzikg @slmosl @sagiben Please review/verify PR #22. 

I've just adapted one of the parameters to match the latest change, and found it working on my box.

**Comment by sagiben** [comment]
One question :
I've noticed that the parameter name was  changed to 'timewated' without
the letter 'i' ?
Is this a typo or the required fix ?

Sagi.

**Comment by itzikg** [comment]
It's okay, it's not a mistake.

**Comment by gklein** [comment]
I know it looks like a typo, but this is the latest change made on the torec site.
I've captured it using Wireshark, and confirmed it to be working on my box. 

Give it a try, lets see if it works for you, before we are merging this fix.

**Comment by itzikg** [comment]
Is there on-site working nonstop to avoid using torec subtitles on kodi

**Comment by sagiben** [comment]
Verified as working ! :+1:
