### ISSUE TITLE
Torec seems to be injecting false subtitles for API downloads

### ISSUE THREAD

**Issue by uriba107** [XBMCil/service.subtitles.torec#25]
Since the last update, subtitles are donwloading again,
however when using as a non registered user (hadn't tried as a registered user, because plugin has no user/password option) I get a bougus srt, where all the text is reading (in hebrew) "please use direct download only" (and things along this line).

I've dug a little into the auth sequence.
it is fairly easy to work around (I think)
you need to post to the http://torec.net/login.asp with a few params and you get an auth cookie back.

I'm adding the curl, I'm not fimiliar with Kodi plugins, so I can at this time help making changes to the plugin.
```
curl http://www.torec.net/login.asp -d "Form=True&site=true&username=<username>&password=<password>&ref=http://www.torec.net/sub.asp?sub_id=43735" -D -
````
ref is a random subtitle, I guess using selcted subtitle ID would be the smart choice.

response was:
```
HTTP/1.1 302 Object moved
Cache-Control: private
Pragma: no-cache
Content-Length: 335
Content-Type: text/html; Charset=utf-8
Expires: Tue, 10 May 2016 02:22:30 GMT
Location: http://www.forom.ws/LoginShare.asp?id=480908&username=<username>&password=96A983ABA881&ref=http%3A%2F%2Fwww%2Etorec%2Enethttp%3A%2F%2Fwww%2Etorec%2Enet%2Fsub%2Easp%3Fsub%5Fid%3D43735&visit=www.torec.net
Server: Apache/2.4.9 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
Set-Cookie: Torec%5FNC%5Fsite=userID=480908&userp=96A983ABA881&user=<username>; expires=Wed, 10-May-2017 02:22:30 GMT; path=/
X-Powered-By: PHP/5.4.27
Date: Tue, 10 May 2016 02:22:30 GMT

<head><title>Object moved</title></head>
<body><h1>Object Moved</h1>This object may be found <a HREF="http://www.forom.ws/LoginShare.asp?id=480908&amp;username=<username>&amp;password=96A983ABA881&amp;ref=http%3A%2F%2Fwww%2Etorec%2Enethttp%3A%2F%2Fwww%2Etorec%2Enet%2Fsub%2Easp%3Fsub%5Fid%3D43735&amp;visit=www.torec.net">here</a>.</body>
```

were the cookie Torec_NC_site has the auth stuff.

HTH,
Uri

**Comment by slmosl** [comment]
fixed in `v1.0.9`
