### ISSUE TITLE
Cannot fetch any subtitles

### ISSUE THREAD

**Issue by orweinberger** [XBMCil/service.subtitles.torec#32]
For a while now, even with an authenticated account, search yield no results for any search phrase.

**Comment by slmosl** [comment]
thanks, @orweinberger, issue started with the new Torec site (ver 7.0), which represents a major UI overhaul for the site (and also demands major changes to this addon).
Will look into it in the near future.

**Comment by slmosl** [comment]
should be fixed in version 1.1.0
