### ISSUE TITLE
התוסף הפסיק לעבוד

### ISSUE THREAD

**Issue by arma123** [XBMCil/service.subtitles.torec#36]
מראה עוד פעם שגיאה הורדת הכתובית נכשלה

יש סיכוי לתקן בבקשה?

**Comment by moshep15** [comment]
everytime time torec addon fixed 2 days after its stop workingi hope permanent solution will be found soon

**Comment by slmosl** [comment]
@arma123 Thanks for bringing the issue to my attention. 
It should be fixed in version 1.1.2.

@moshep15 I semi-agree with you, but note that websites changes all the time, and Torec is no different. Scraping is not for the faint of heart 😄

**Comment by moshep15** [comment]
yeah scraping issue not so easy i am aware of that many changes are comming from the other side and  the programer must be on the run all the time.
