### ISSUE TITLE
Generate a fake token instead of waiting the ~13 seconds

### ISSUE THREAD

**Issue by yosi-dediashvili** [XBMCil/service.subtitles.torec#46]
Hi

Back in the days were I was working on SubiT I was trying to bypass the wait time for un-registered downloads from Torec.

I was able to do that (see the gist: https://gist.github.com/yosi-dediashvili/276fe50f25579819a926).

My plan was to add it with the release of SubiT 3, but I never got there :\

I think it would be a nice add to this plugin.

I see that it no longer works, but it might work with small adjustments - worth a try.

**Comment by slmosl** [comment]
great job, @yosi-dediashvili, integrated it with version 1.3.0

**Comment by yosi-dediashvili** [comment]
Yay :}
